#!/bin/sh
# This script is called from the vpnc.conf
#    ...
#    ...
#    Script /opt/vpnc/etc/juniper_split
# 2013 ml4711

# Add one IP to the list of split tunnel
add_ip ()
{
    export CISCO_SPLIT_INC_${CISCO_SPLIT_INC}_ADDR=$1
    export CISCO_SPLIT_INC_${CISCO_SPLIT_INC}_MASK=$2
    export CISCO_SPLIT_INC_${CISCO_SPLIT_INC}_MASKLEN=$3
    export CISCO_SPLIT_INC=$(($CISCO_SPLIT_INC + 1))
}

# Initialize empty split tunnel list
export CISCO_SPLIT_INC=0

# Delete DNS info provided by VPN server to use internet DNS
# Comment following line to use DNS beyond VPN tunnel
unset INTERNAL_IP4_DNS

# List of IPs or Nets beyond VPN tunnel
add_ip 192.168.2.0 255.255.255.0 24
add_ip 192.168.3.0 255.255.255.0 24

# Execute (i.e source) default script
. /usr/local/opt/vpnc/etc/vpnc/vpnc-script
# End of script
